const PROFILE = 'PROFILE';
const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
const PROFILE_ERROR = 'PROFILE_ERROR';
const PROFILE_RESET_ALERT = 'PROFILE_RESET_ALERT';

export {
    PROFILE,
    PROFILE_SUCCESS,
    PROFILE_ERROR,
    PROFILE_RESET_ALERT
};