const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';
const LOGIN_RESET_ALERT = 'LOGIN_RESET_ALERT';
const ADD_SKILL = 'ADD_SKILL';
const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
const ADD_SKILL_ERROR = 'ADD_SKILL_ERROR';
const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
const ADD_EXPERIENCE_ERROR = 'ADD_EXPERIENCE_ERROR';
const ADD_EDUCATION = 'ADD_EDUCATION';
const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
const ADD_EDUCATION_ERROR = 'ADD_EDUCATION_ERROR';
export {
    LOGIN,
    LOGIN_ERROR,
    LOGIN_SUCCESS,
    LOGOUT,
    LOGIN_RESET_ALERT,
    ADD_SKILL,
    ADD_SKILL_SUCCESS,
    ADD_SKILL_ERROR,
    ADD_EXPERIENCE,
    ADD_EXPERIENCE_SUCCESS,
    ADD_EXPERIENCE_ERROR,
    ADD_EDUCATION,
    ADD_EDUCATION_SUCCESS,
    ADD_EDUCATION_ERROR
};