const FORGOT = 'FORGOT';
const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
const FORGOT_ERROR = 'FORGOT_ERROR';
const FORGOT_RESET_ALERT = 'FORGOT_RESET_ALERT';

export {
    FORGOT,
    FORGOT_SUCCESS,
    FORGOT_ERROR,
    FORGOT_RESET_ALERT
};